root: true
env:
  browser: true
  es2021: true
  node: true
ignorePatterns:
  - node_modules/*
  - dist/*
  - "!.prettierrc.js"
extends:
  - plugin:nuxt/recommended
  - plugin:vue/vue3-essential
  - plugin:prettier/recommended     # plugin과 eslint-config-prettier 설정을 한번에.
overrides: []
parser: vue-eslint-parser
parserOptions:
  ts: "@typescript-eslint/parser"
  ecmaVersion: latest               # 사용할 ECMA버전 설정
  sourceType: module                # parser의 export 형태 설정
  project: ./tsconfig.json
plugins:
  - vue
  - prettier
  - '@typescript-eslint'
rules: 
  prettier/prettier:
  - error
  - {}
  vue/multi-word-component-names:
  - 0
