env:
  browser: true
  es2021: true
  node: true
ignorePatterns:
  - node_modules/*
  - dist/*
  - "!.prettierrc.js"
extends:
  - plugin:nuxt/recommended
  - plugin:vue/vue3-essential
  - standard-with-typescript
  - plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - vue
  - prettier
rules: 
  prettier/prettier:
  - error
  - {}
