env:
  browser: true
  es2021: true
  node: true
ignorePatterns:
  - node_modules/*
  - dist/*
  - "!.prettierrc.js"
extends:
  - plugin:nuxt/recommended
  - plugin:vue/vue3-essential
  - standard-with-typescript
  - plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest               # 사용할 ECMA버전 설정
  sourceType: module                # parser의 export 형태 설정
  project: ./tsconfig.json
plugins:
  - vue
  - prettier
rules: 
  prettier/prettier:
  - error
  - {}
