version: '3.7'

services:
  nuxt_app:
    image: hunkicho/jg_front_nuxt:latest
    ports:
      - '3000:3000'

  nginx:
    image: hunkicho/jg_front_nginx:latest
    ports:
      - '80:80'
    volumes:
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - nuxt_app